apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-go-sample-app
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ops/overlays/prod
    repoURL: https://github.com/andreasevers/go-sample-app.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
